name: CI
on:
  push:
    branches: [main]
env:
    DOCKER_REGISTRY: <<your_image_registry_URL>>
    DOCKER_REPOSITORY: <<your_image_repository>>
    image_name:  <<image_name>>

jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    steps:
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

       
     #- name: Set up Docker Daemon to allow insecure registries.
      # run: |
       # sudo mkdir -p /etc/docker
        #echo '{ "insecure-registries":["166.0.162.207"] }' | sudo tee /etc/docker/daemon.json
        #sudo systemctl restart docker
###
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
            username: ${{ secrets.DOCKERHUB_USERNAME }} ### your registry username
            password: ${{ secrets.DOCKERHUB_TOKEN }}    ### your registry password
            registry:                                   ### your registry URL

     - name: Build and Push
       uses: docker/build-push-action@v3
       with:
          push: true
          tags: $DOCKER_REGISTRY/$DOCKER_REPOSITORY/$image_name:${{ github.sha }}


     - name: Update Version
       run: |
           git config --global user.email "your_email"
           git config --global user.name "your_github_username" 
           git clone https://${{ secrets.GIT_TOKEN }}@github.com/<<your username>>/helmchart.git
           cd helmchart
           tag=$(cat ./values.yaml |grep myimage | awk -F":" '{print $3}')
           #sed -i "s/$tag/${{ github.shd }}"  ./values.yaml
           new_tag=${{ github.sha }}
           sed -i "s|:$tag\$|:$new_tag|" ./values.yaml
           git add .
           git commit -m "$DOCKER_REPOSITORY/$image_name:${{ github.sha }}"
           git push
